### ISSUE TITLE
ITS and PrEP Issues

### ISSUE THREAD

**Issue by ejcumbana** [usaid-mozambique/sismar#13]
Hi Joe,

PrEP:
1. In datasets dbprev, we have the indicator  "3 meses consecutivos" for PrEP, it should be removed, we don't have this indicator in actual resumo mensal
2. The varieble "Outro" of grupo alvo it's only desagregated for PREP_ELIG_PERIODO. It should be desagregated for all indicador. Should be desagregated too for PRE_NOVOS_PERIODO, PREP_NOVOS_RETORN and PREP_REC_PERIODO.
3. In the "Grupo Alvo" we have the condition of the pregnant and lactating woman included, it must be removed. There should only be pregnant and lactating women at risk
 
ITS:
1. For the indicator "Populacao Pertence" we would like to have the desagregation of "SIM" or "NAO"

**Comment by josephlara** [comment]
All issues address!
