### ISSUE TITLE
ATS Issues

### ISSUE THREAD

**Issue by ejcumbana** [usaid-mozambique/sismar#16]
Fonte - db_ats:

•	Não temos disponível o indicador de confirmação de autoteste para a fonte LdR ATS , devemos ter conforme o SISMA;

•	Na variável “resultado_estado”, não temos disponível o resultado “indeterminado” para a fonte LdR ATS, devemos ter conforme o SISMA;

•	Temos o indicador ATS_TST_POS no db_ats, mas esse indicador deve ser codificado como ATS_TST como vem no sisma_var_mapping 20240201.

**Comment by josephlara** [comment]
resolved.
