### ISSUE TITLE
Convert age coding

### ISSUE THREAD

**Issue by josephlara** [usaid-mozambique/sismar#7]
Team would like to have the under 5 year age group coded uniformly as 0-4 (currently it varies, commonly <05).  The team would also like to convert 05-09 to 5-9

**Comment by josephlara** [comment]
<05 age recoded to 0-4 (only change required was to data_sisma_hiv_ajmhcmm_map)

**Comment by ejcumbana** [comment]
Hi Joe, will we sitll have 05 - 09 converted?
